import type { User, RoleDefinition, UserPermission, AuditLogEntry, UserRole } from "./types";

export const PERMISSIONS_CATALOG: UserPermission[] = [
  {
    id: "view_telemetry",
    name: "View Telemetry & Dashboards",
    description: "Access live flow telemetry, main threat chart, and metrics overview.",
    category: "Alert Operations",
  },
  {
    id: "triage_alerts",
    name: "Triage & Inspect Alerts",
    description: "Inspect flow features, view TreeSHAP feature impact bars and MITRE tactics.",
    category: "Alert Operations",
  },
  {
    id: "label_false_positives",
    name: "Label False Positives",
    description: "Mark benign alerts as false alarms and supply labels for model retraining.",
    category: "Alert Operations",
  },
  {
    id: "escalate_incidents",
    name: "Escalate Incidents (Tier-3)",
    description: "Trigger incident response playbooks and assign high-confidence alerts.",
    category: "Incident Response",
  },
  {
    id: "trigger_candidate_retrain",
    name: "Trigger Candidate Retraining",
    description: "Initiate offline retraining pipeline with analyst-labeled training rows.",
    category: "Model Governance",
  },
  {
    id: "promote_model",
    name: "Promote Model to Production",
    description: "Approve candidate model promotion after verifying leakage-free test split.",
    category: "Model Governance",
  },
  {
    id: "configure_drift_thresholds",
    name: "Configure Drift & Thresholds",
    description: "Tune PSI drift warning/drift bands and analyst false-alert budget.",
    category: "Model Governance",
  },
  {
    id: "manage_users_rbac",
    name: "Manage Users & Access Control",
    description: "Invite users, modify analyst roles, suspend access, and audit SecOps team.",
    category: "Administration",
  },
];

export const ROLE_DEFINITIONS: Record<UserRole, RoleDefinition> = {
  admin: {
    id: "admin",
    title: "SOC Lead",
    tier: "Lead",
    shortLabel: "ADMIN",
    description: "Unrestricted access across all operational, ML governance, and user management systems.",
    badgeBg: "rgba(139, 95, 191, 0.12)",
    badgeText: "#D8B4FE",
    badgeBorder: "rgba(139, 95, 191, 0.28)",
    permissions: [
      "view_telemetry",
      "triage_alerts",
      "label_false_positives",
      "escalate_incidents",
      "trigger_candidate_retrain",
      "promote_model",
      "configure_drift_thresholds",
      "manage_users_rbac",
    ],
  },
  tier_3: {
    id: "tier_3",
    title: "Senior Responder",
    tier: "Tier-3",
    shortLabel: "TIER-3",
    description: "Senior incident response specialist. Authorizes incident containment, candidate retrains, and model promotions.",
    badgeBg: "rgba(239, 68, 68, 0.12)",
    badgeText: "#FCA5A5",
    badgeBorder: "rgba(239, 68, 68, 0.28)",
    permissions: [
      "view_telemetry",
      "triage_alerts",
      "label_false_positives",
      "escalate_incidents",
      "trigger_candidate_retrain",
      "promote_model",
    ],
  },
  tier_2: {
    id: "tier_2",
    title: "SecOps Analyst",
    tier: "Tier-2",
    shortLabel: "TIER-2",
    description: "Active frontline threat triage. Analyzes SHAP attributions, escalates novel attacks, and labels false positives.",
    badgeBg: "rgba(59, 130, 246, 0.12)",
    badgeText: "#93C5FD",
    badgeBorder: "rgba(59, 130, 246, 0.28)",
    permissions: [
      "view_telemetry",
      "triage_alerts",
      "label_false_positives",
      "escalate_incidents",
    ],
  },
  tier_1: {
    id: "tier_1",
    title: "Triage Specialist",
    tier: "Tier-1",
    shortLabel: "TIER-1",
    description: "First responder for initial flow alerts and real-time monitoring. Forwards high severity threats to Tier-2.",
    badgeBg: "rgba(16, 185, 129, 0.12)",
    badgeText: "#6EE7B7",
    badgeBorder: "rgba(16, 185, 129, 0.28)",
    permissions: [
      "view_telemetry",
      "triage_alerts",
    ],
  },
  auditor: {
    id: "auditor",
    title: "Compliance Auditor",
    tier: "Auditor",
    shortLabel: "AUDITOR",
    description: "Read-only access to evaluation reports, model cards, drift curves, and incident logs for compliance.",
    badgeBg: "rgba(245, 158, 11, 0.12)",
    badgeText: "#FCD34D",
    badgeBorder: "rgba(245, 158, 11, 0.28)",
    permissions: [
      "view_telemetry",
    ],
  },
};

export const INITIAL_USERS: User[] = [
  {
    id: "usr_satveek",
    name: "Satveek Gupta",
    email: "satveek.gupta@netwatch.internal",
    role: "admin",
    status: "active",
    department: "SecOps Leadership",
    twoFactorEnabled: true,
    avatarColor: "#8B5FBF",
    initials: "SG",
    lastActive: "Just now",
    createdAt: "2026-06-01",
    shift: "Global Lead",
    assignedAlertsCount: 4,
  },
  {
    id: "usr_raghav",
    name: "Raghav Sharma",
    email: "raghav.sharma@netwatch.internal",
    role: "tier_3",
    status: "active",
    department: "Incident Response",
    twoFactorEnabled: true,
    avatarColor: "#EF4444",
    initials: "RS",
    lastActive: "6m ago",
    createdAt: "2026-07-10",
    shift: "On-Call Tier 3",
    assignedAlertsCount: 7,
  },
  {
    id: "usr_mrigank",
    name: "Mrigank Bhatnagar",
    email: "mrigank.bhatnagar@netwatch.internal",
    role: "tier_2",
    status: "active",
    department: "SOC Day Shift",
    twoFactorEnabled: true,
    avatarColor: "#3B82F6",
    initials: "MB",
    lastActive: "12m ago",
    createdAt: "2026-08-15",
    shift: "08:00 - 16:00 UTC",
    assignedAlertsCount: 15,
  },
  {
    id: "usr_shivam",
    name: "Shivam Rai",
    email: "shivam.rai@netwatch.internal",
    role: "tier_2",
    status: "active",
    department: "Threat Intelligence & Forensics",
    twoFactorEnabled: true,
    avatarColor: "#6366F1",
    initials: "SR",
    lastActive: "24m ago",
    createdAt: "2026-08-20",
    shift: "12:00 - 20:00 UTC",
    assignedAlertsCount: 11,
  },
  {
    id: "usr_singhvrat",
    name: "Singhvrat Singh",
    email: "singhvrat.singh@netwatch.internal",
    role: "tier_1",
    status: "active",
    department: "SOC Night Shift",
    twoFactorEnabled: true,
    avatarColor: "#10B981",
    initials: "SS",
    lastActive: "45m ago",
    createdAt: "2026-09-01",
    shift: "00:00 - 08:00 UTC",
    assignedAlertsCount: 21,
  },
  {
    id: "usr_arnav",
    name: "Arnav Katyal",
    email: "arnav.katyal@netwatch.internal",
    role: "auditor",
    status: "active",
    department: "Risk & Governance",
    twoFactorEnabled: true,
    avatarColor: "#F59E0B",
    initials: "AK",
    lastActive: "Yesterday",
    createdAt: "2026-08-01",
    shift: "Governance Shift",
    assignedAlertsCount: 0,
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    id: "aud_01",
    timestamp: "2026-10-05 20:45:12",
    actorName: "Satveek Gupta",
    actorRole: "admin",
    action: "ROLE_MODIFIED",
    target: "Singhvrat Singh",
    details: "Assigned Tier-1 Triage Specialist role with hardware MFA requirement enforced.",
    severity: "info",
  },
  {
    id: "aud_02",
    timestamp: "2026-10-05 19:12:04",
    actorName: "Raghav Sharma",
    actorRole: "tier_3",
    action: "INCIDENT_ESCALATED",
    target: "Alert #ALT-9081",
    details: "Escalated high-confidence SYN Flood targeting primary database cluster to Tier-3.",
    severity: "warning",
  },
  {
    id: "aud_03",
    timestamp: "2026-10-05 18:30:55",
    actorName: "Mrigank Bhatnagar",
    actorRole: "tier_2",
    action: "ALERT_LABELED_FALSE_POSITIVE",
    target: "Alert #ALT-8994",
    details: "Verified backup synchronization burst misclassified by Isolation Forest anomaly detector.",
    severity: "info",
  },
  {
    id: "aud_04",
    timestamp: "2026-10-05 16:50:18",
    actorName: "Shivam Rai",
    actorRole: "tier_2",
    action: "THREAT_HUNT_LOGGED",
    target: "Subnet 192.168.10.0/24",
    details: "Flagged low-and-slow port sweep pattern matching novel reconnaissance campaign.",
    severity: "warning",
  },
  {
    id: "aud_05",
    timestamp: "2026-10-04 14:20:10",
    actorName: "Satveek Gupta",
    actorRole: "admin",
    action: "THRESHOLD_UPDATED",
    target: "False Alert Budget",
    details: "Tightened false-alert budget constraint to <= 2.0 per 10k flows.",
    severity: "warning",
  },
  {
    id: "aud_06",
    timestamp: "2026-10-03 11:15:40",
    actorName: "Arnav Katyal",
    actorRole: "auditor",
    action: "COMPLIANCE_REVIEW_COMPLETED",
    target: "Q3 SOC Governance",
    details: "Verified zero-leakage training protocol and model drift thresholds for ISO compliance.",
    severity: "info",
  },
];

export function getInitials(name: string): string {
  const parts = name.trim().split(" ");
  if (parts.length === 1) return parts[0].slice(0, 2).toUpperCase();
  return (parts[0][0] + parts[parts.length - 1][0]).toUpperCase();
}
