"""ml/evaluate/report.py — handbook-required named file.

The evaluation report is generated by ml/train.py into reports/metrics.json
and rendered into docs/model_card.md by ml/evaluate/model_card.py.
This module provides a thin convenience wrapper that replicates make evaluate
in one function call.

Usage:
    python -m ml.evaluate.report
"""
from __future__ import annotations

import json
import subprocess
import sys
from pathlib import Path


def generate(config_path: str = "ml/config.yaml") -> Path:
    """Re-run model-card generation and return the output path.

    This does *not* retrain. It reads reports/metrics.json (written by
    make train) and regenerates docs/model_card.md.  Run `make train`
    first.
    """
    from ml.evaluate.model_card import render

    render()
    out = Path("docs/model_card.md")
    return out


if __name__ == "__main__":
    out = generate()
    print(f"report written to {out}")
