apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netwatch-data-pvc
  namespace: netwatch
  labels:
    app.kubernetes.io/name: netwatch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: netwatch-models-pvc
  namespace: netwatch
  labels:
    app.kubernetes.io/name: netwatch
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
